server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: food
          uri: lb://EFOODSHOP/
          predicates:
            - Path=/food/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
