server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: food
          uri: lb://FOOD/
          predicates:
            - Path=/food/**
        - id: storage
          uri: lb://STORAGE/
          predicates:
            - Path=/storage/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
