server:
  port: &port 9000

spring:
  application:
    name: shipper
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: EFOODSHOP
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update

app-config:
  shipper:
    hostname: 'http://localhost'
    port: *port
    page-size: 5
  virtual_food_cart_order:
    hostname: 'http://localhost'
    port: 9002
    page-size: 5

