-- Create user EFOODSHOP
CREATE USER EFOODSHOP IDENTIFIED BY 123456;

-- Assign all permissions to the user
GRANT ALL PRIVILEGES TO EFOODSHOP;


-- Add ROLE data
INSERT ALL
    INTO ROLE ( ID, ROLE_NAME ) VALUES (1, 'MANAGER')
	INTO ROLE ( ID, ROLE_NAME ) VALUES (2, 'SHIPPER')
	INTO ROLE ( ID, ROLE_NAME ) VALUES (3, 'CUSTOMER')
SELECT 1 FROM DUAL;

-- Add SHIPPER data
INSERT ALL
    INTO USER_1 ( ID, USERNAME, PASSWORD, FULLNAME, PHONE, ROLE_ID ) VALUES (1, 'luck', '123456', 'Nguyễn Hoàng Linh', '0933348791', 2)
	INTO USER_1 ( ID, USERNAME, PASSWORD, FULLNAME, PHONE, ROLE_ID ) VALUES (2, 'alice', '123456', 'Alice', '0123456001', 2)
	INTO USER_1 ( ID, USERNAME, PASSWORD, FULLNAME, PHONE, ROLE_ID ) VALUES (3, 'bob', '123456', 'Bob', '0123456002', 2)
SELECT 1 FROM DUAL;

-- Add Order data
INSERT ALL
    INTO ORDER_1 ( ID, CART_ID, CREATED_DATE, ADDRESS, SHIPPER_ID, SHIPPING_STATUS) VALUES (1, 1, SYSDATE, 'Thủ Đức, TPHCM', 1, 'IN_PROGRESS')
    INTO ORDER_1 ( ID, CART_ID, CREATED_DATE, ADDRESS, SHIPPER_ID, SHIPPING_STATUS) VALUES (2, 2, SYSDATE, 'Thủ Đức, TPHCM', 1, 'DELIVERED')
    INTO ORDER_1 ( ID, CART_ID, CREATED_DATE, ADDRESS, SHIPPER_ID, SHIPPING_STATUS) VALUES (3, 3, SYSDATE, 'Thủ Đức, TPHCM', null, 'IN_PROGRESS')
    INTO ORDER_1 ( ID, CART_ID, CREATED_DATE, ADDRESS, SHIPPER_ID, SHIPPING_STATUS) VALUES (4, 4, SYSDATE, 'Thủ Đức, TPHCM', null, 'IN_PROGRESS')
    INTO ORDER_1 ( ID, CART_ID, CREATED_DATE, ADDRESS, SHIPPER_ID, SHIPPING_STATUS) VALUES (5, 5, SYSDATE, 'Thủ Đức, TPHCM', null, 'IN_PROGRESS')
SELECT 1 FROM DUAL;



UPDATE USER_1 SET PASSWORD = 123456, FULLNAME = 'Nguyễn Hoàng Linh', PHONE = '0933348791' WHERE ID = 1


SELECT * FROM ORDER_1

SELECT * FROM USER_1

