-- Create user EFOODSHOP
CREATE USER EFOODSHOP IDENTIFIED BY 123456;

-- Assign all permissions to the user
GRANT ALL PRIVILEGES TO EFOODSHOP;


-- Add ROLE data
INSERT ALL
    INTO ROLE ( ID, ROLE_NAME ) VALUES (1, 'MANAGER')
	INTO ROLE ( ID, ROLE_NAME ) VALUES (2, 'SHIPPER')
	INTO ROLE ( ID, ROLE_NAME ) VALUES (3, 'CUSTOMER')
SELECT 1 FROM DUAL;

-- Add SHIPPER data
INSERT ALL
    INTO USER_1 ( ID, USERNAME, PASSWORD, PHONE, ROLE_ID ) VALUES (1, 'luck', 'Nguyễn Hoàng Linh', '0933348791', 2)
	INTO USER_1 ( ID, USERNAME, PASSWORD, PHONE, ROLE_ID ) VALUES (2, 'alice', 'Alice', '0123456001', 2)
	INTO USER_1 ( ID, USERNAME, PASSWORD, PHONE, ROLE_ID ) VALUES (3, 'bob', 'Bob', '0123456002', 2)
SELECT 1 FROM DUAL;

-- Add Order data
INSERT ALL
    INTO ORDER_1 ( ID, CART_ID, SHIPPER_ID, SHIPPING_STATUS) VALUES (1, 1, 1, 'IN_PROGRESS')
    INTO ORDER_1 ( ID, CART_ID, SHIPPER_ID, SHIPPING_STATUS) VALUES (2, 2, 1, 'DELIVERED')
    INTO ORDER_1 ( ID, CART_ID, SHIPPER_ID, SHIPPING_STATUS) VALUES (3, 3, null, 'IN_PROGRESS')
    INTO ORDER_1 ( ID, CART_ID, SHIPPER_ID, SHIPPING_STATUS) VALUES (4, 4, null, 'IN_PROGRESS')
    INTO ORDER_1 ( ID, CART_ID, SHIPPER_ID, SHIPPING_STATUS) VALUES (5, 5, null, 'IN_PROGRESS')
SELECT 1 FROM DUAL;